const APP_NAME = "Question Bank";
const COPYRIGHT =
  "All rights reserved. For personal study use only. Reproduction or redistribution without permission is prohibited.";

export function exportCopyrightLine() {
  return `© ${new Date().getFullYear()} ${APP_NAME}. ${COPYRIGHT}`;
}

type ExportQuestion = {
  type: string;
  question: string;
  options?: string[] | null;
  answer?: unknown;
  topic?: string | null;
  domain?: string | null;
};

function formatAnswer(answer: unknown): string {
  if (answer == null) return "—";
  if (typeof answer === "boolean") return answer ? "True" : "False";
  if (typeof answer === "string") return answer;
  return JSON.stringify(answer, null, 2);
}

export function formatQuestionsAsText(
  materialTitle: string,
  questions: ExportQuestion[],
  includeAnswers: boolean
) {
  const lines: string[] = [
    materialTitle,
    `${questions.length} question${questions.length === 1 ? "" : "s"}`,
    "",
  ];

  questions.forEach((item, index) => {
    lines.push(`${index + 1}. [${item.type}] ${item.question}`);
    if (item.topic) lines.push(`   Topic: ${item.topic}`);
    if (item.options?.length) {
      item.options.forEach((option, optionIndex) => {
        lines.push(`   ${String.fromCharCode(65 + optionIndex)}. ${option}`);
      });
    }
    if (includeAnswers) {
      lines.push(`   Answer: ${formatAnswer(item.answer)}`);
    }
    lines.push("");
  });

  lines.push("—".repeat(48));
  lines.push(exportCopyrightLine());

  return lines.join("\n");
}

export function formatQuestionsAsHtml(
  materialTitle: string,
  questions: ExportQuestion[],
  includeAnswers: boolean
) {
  const body = questions
    .map((item, index) => {
      const options = item.options?.length
        ? `<ul>${item.options
            .map(
              (option, optionIndex) =>
                `<li><strong>${String.fromCharCode(65 + optionIndex)}.</strong> ${escapeHtml(option)}</li>`
            )
            .join("")}</ul>`
        : "";

      const answer = includeAnswers
        ? `<p class="answer"><strong>Answer:</strong> ${escapeHtml(formatAnswer(item.answer))}</p>`
        : "";

      const topic = item.topic
        ? `<p class="meta">Topic: ${escapeHtml(item.topic)}</p>`
        : "";

      return `
        <section class="question">
          <h3>${index + 1}. <span class="type">${escapeHtml(item.type)}</span></h3>
          <p class="prompt">${escapeHtml(item.question)}</p>
          ${topic}
          ${options}
          ${answer}
        </section>
      `;
    })
    .join("");

  return `<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>${escapeHtml(materialTitle)} — ${APP_NAME}</title>
    <style>
      body { font-family: Georgia, serif; color: #0e1422; padding: 32px; line-height: 1.5; }
      h1 { font-size: 24px; margin-bottom: 4px; }
      .subtitle { color: #64748b; margin-bottom: 24px; }
      .question { margin-bottom: 20px; page-break-inside: avoid; }
      .type { color: #48b89a; font-size: 12px; font-weight: 700; }
      .meta { color: #64748b; font-size: 13px; }
      .answer { margin-top: 8px; padding: 10px 12px; background: #e8f8ef; border-radius: 8px; }
      ul { margin: 8px 0 0 18px; }
      footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #d8e0ea; font-size: 11px; color: #64748b; }
    </style>
  </head>
  <body>
    <h1>${escapeHtml(materialTitle)}</h1>
    <p class="subtitle">${questions.length} question${questions.length === 1 ? "" : "s"} · Generated by ${APP_NAME}</p>
    ${body}
    <footer>${escapeHtml(exportCopyrightLine())}</footer>
  </body>
</html>`;
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
